-- Phase 2: analytics_events and analytics_daily_rollups.
-- Terminology: "Unique Sessions", never "Unique Visitors". No
-- fingerprinting, no persistent human identity, no raw IP storage, no raw
-- user agent storage.

create table public.analytics_events (
  id uuid primary key default gen_random_uuid(),
  restaurant_id uuid not null references public.restaurants (id) on delete cascade,
  branch_id uuid references public.branches (id) on delete cascade,
  event_type public.analytics_event_type not null,
  product_id uuid references public.products (id) on delete set null,
  category_id uuid references public.categories (id) on delete set null,
  anon_session_id uuid not null,
  device_type text,
  country text,
  traffic_source text,
  occurred_at timestamptz not null default now()
);

create index analytics_events_restaurant_id_occurred_at_idx on public.analytics_events (restaurant_id, occurred_at);
create index analytics_events_branch_id_occurred_at_idx on public.analytics_events (branch_id, occurred_at);
create index analytics_events_event_type_idx on public.analytics_events (event_type);

-- One unified rollups table, branch-aware (a null branch_id row is a
-- restaurant-wide rollup). Shaped so dashboard reporting can later return
-- views, unique sessions, product/category/branch views, QR scans, contact
-- clicks, top products/categories, traffic sources, device types,
-- countries, and date ranges without further schema changes.
create table public.analytics_daily_rollups (
  id uuid primary key default gen_random_uuid(),
  restaurant_id uuid not null references public.restaurants (id) on delete cascade,
  branch_id uuid references public.branches (id) on delete cascade,
  rollup_date date not null,
  menu_views integer not null default 0,
  unique_sessions integer not null default 0,
  branch_views integer not null default 0,
  qr_scans integer not null default 0,
  whatsapp_clicks integer not null default 0,
  phone_clicks integer not null default 0,
  instagram_clicks integer not null default 0,
  google_maps_clicks integer not null default 0,
  product_views jsonb not null default '{}'::jsonb,
  category_views jsonb not null default '{}'::jsonb,
  top_products jsonb,
  top_categories jsonb,
  traffic_sources jsonb,
  device_types jsonb,
  countries jsonb,
  created_at timestamptz not null default now(),
  unique (restaurant_id, branch_id, rollup_date)
);

create index analytics_daily_rollups_restaurant_id_date_idx on public.analytics_daily_rollups (restaurant_id, rollup_date);
create index analytics_daily_rollups_branch_id_date_idx on public.analytics_daily_rollups (branch_id, rollup_date);

alter table public.analytics_events enable row level security;
alter table public.analytics_events force row level security;

alter table public.analytics_daily_rollups enable row level security;
alter table public.analytics_daily_rollups force row level security;

-- analytics_events ----------------------------------------------------
-- These rows are generated by anonymous public-menu visitors (menu_view,
-- qr_scan, whatsapp_click, etc.), so both anon and authenticated may
-- INSERT — gated by a WITH CHECK that the entire referenced chain is
-- internally consistent, to keep this from being an open write to
-- arbitrary tenant ids. There is no anonymous SELECT — raw events are
-- staff-facing.
--
-- The chain validation is a SECURITY DEFINER function, not an inline join
-- in the policy, because categories/products/menus (migration 07) have
-- FORCE ROW LEVEL SECURITY and no anon-facing SELECT policy at all — an
-- inline EXISTS join against those tables in a WITH CHECK clause runs as
-- the inserting role, so for anon it would be silently filtered to zero
-- rows by RLS regardless of whether the chain is actually valid, which
-- would reject every legitimate category_id/product_id from anon, not
-- just mismatched ones. analytics_event_chain_valid() runs as its
-- SECURITY DEFINER owner, bypassing that RLS, to check pure structural
-- tenant-chain validity without granting either role any broader SELECT
-- access to the draft menu tables.
create or replace function public.analytics_event_chain_valid(
  target_restaurant_id uuid,
  target_branch_id uuid,
  target_category_id uuid,
  target_product_id uuid
)
returns boolean
language sql
security definer
stable
set search_path = ''
as $$
  select
    exists (
      select 1 from public.restaurants r
      where r.id = target_restaurant_id and r.status = 'active'
    )
    and (
      target_branch_id is null
      or exists (
        select 1 from public.branches b
        where b.id = target_branch_id
          and b.restaurant_id = target_restaurant_id
          and b.status = 'active'
      )
    )
    and (
      target_category_id is null
      or exists (
        select 1
        from public.categories c
        join public.menus m on m.id = c.menu_id
        join public.branches b on b.id = m.branch_id
        where c.id = target_category_id
          and b.restaurant_id = target_restaurant_id
          and (target_branch_id is null or b.id = target_branch_id)
      )
    )
    and (
      target_product_id is null
      or exists (
        select 1
        from public.products p
        join public.categories c on c.id = p.category_id
        join public.menus m on m.id = c.menu_id
        join public.branches b on b.id = m.branch_id
        where p.id = target_product_id
          and b.restaurant_id = target_restaurant_id
          and (target_branch_id is null or b.id = target_branch_id)
          and (target_category_id is null or c.id = target_category_id)
      )
    );
$$;

-- SECURITY DEFINER function EXECUTE audit: called directly from the
-- analytics_events INSERT WITH CHECK below, which is the only anon-facing
-- write path in the whole schema — so, unlike every other helper in this
-- codebase, this is the one function that legitimately needs an anon
-- EXECUTE grant. It only ever returns a boolean (never row data), so
-- granting anon EXECUTE does not expose any draft menu content that
-- anon's ordinary (RLS-governed) SELECT privileges wouldn't already allow
-- it to attempt and be refused.
revoke all on function public.analytics_event_chain_valid(uuid, uuid, uuid, uuid) from public;
grant execute on function public.analytics_event_chain_valid(uuid, uuid, uuid, uuid) to anon, authenticated;

-- Every reference an event carries is validated against the SAME event
-- row's other references, not just checked to exist somewhere: branch_id
-- (if set) must belong to restaurant_id; category_id (if set) must
-- resolve category -> menu -> branch -> restaurant to that same
-- restaurant_id (and to branch_id, when branch_id is also set);
-- product_id (if set) must resolve product -> category -> menu -> branch
-- -> restaurant to that same restaurant_id/branch_id, and to category_id
-- when that is also set. This is what stops "restaurant A's event
-- referencing restaurant B's product/category" tenant poisoning — a
-- narrower per-column existence check (e.g. "does this product_id exist
-- in some restaurant") would not catch a mismatched combination. A null
-- category_id/product_id is always fine — plenty of event types
-- (menu_view, qr_scan, whatsapp_click, ...) carry neither.
create policy analytics_events_insert_public on public.analytics_events
  for insert to anon, authenticated
  with check (
    public.analytics_event_chain_valid(restaurant_id, branch_id, category_id, product_id)
  );

create policy analytics_events_select_viewers on public.analytics_events
  for select to authenticated
  using (
    case
      when branch_id is not null then public.has_capability(branch_id, 'analytics.view')
      else exists (
        select 1 from public.restaurant_members m
        where m.restaurant_id = analytics_events.restaurant_id
          and m.user_id = auth.uid()
          and m.status = 'active'
          and m.role in ('owner', 'admin')
      )
    end
  );

-- analytics_daily_rollups -------------------------------------------------
-- Aggregation is a trusted server-side batch job in a later phase; no
-- authenticated/anon write policy exists yet (fail closed by default).

create policy analytics_daily_rollups_select_viewers on public.analytics_daily_rollups
  for select to authenticated
  using (
    case
      when branch_id is not null then public.has_capability(branch_id, 'analytics.view')
      else exists (
        select 1 from public.restaurant_members m
        where m.restaurant_id = analytics_daily_rollups.restaurant_id
          and m.user_id = auth.uid()
          and m.status = 'active'
          and m.role in ('owner', 'admin')
      )
    end
  );
